Repository DefCon-Apps/ECOmunity-FE, pull requests merged in 2022-09, with the labels that each got.

#7 Main Page Layout
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/components/MyPoint.tsx
  src/components/Nav.tsx
  src/components/Title.tsx
  src/pages/Main.tsx
  src/styles/GlobalStyle.tsx
  src/styles/MainStyle.tsx
  src/styles/NavStyle.tsx
Labels: help wanted

#8 파이어베이스 로그인 추가
  .gitignore
  package-lock.json
  package.json
  src/auth/index.ts
  src/components/MyPoint.tsx
  src/pages/Login.tsx
Labels: enhancement

#11 게시글 작성 기능 추가
  src/components/Modal.tsx
  src/components/PostWrite.tsx
  src/pages/Login.tsx
  src/pages/Post.tsx
Labels: enhancement

#12 Notice layout
  src/components/NoticeDeco.tsx
  src/components/NoticeThumbnail.tsx
  src/components/Title.tsx
  src/pages/Main.tsx
  src/pages/Notice.tsx
Labels: enhancement

#14 Profile layout 완성
  src/components/ProfileBgImg.tsx
  src/components/ProfileImg.tsx
  src/components/ProfileIntro.tsx
  src/components/ProfilePoint.tsx
  src/pages/Profile.tsx
Labels: enhancement

#17 Docker 배포설정 / Jenkins 빌드설정 적용
  .dockerignore
  Dockerfile
  Jenkinsfile
Labels: enhancement

#18 Profile design
  package-lock.json
  package.json
  src/App.tsx
  src/components/Nav.tsx
  src/components/NavBase.tsx
  src/components/ProfileBg.tsx
  src/components/ProfileBgImg.tsx
  src/components/ProfileImg.tsx
  src/components/ProfileIntro.tsx
  src/components/ProfilePoint.tsx
  src/index.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/Profile.tsx
  src/redux/store.tsx
Labels: enhancement

#20 Main page design
  src/components/MyPoint.tsx
  src/components/Nav.tsx
  src/components/NavBase.tsx
  src/components/Title.tsx
  src/index.tsx
  src/pages/Main.tsx
  src/pages/MainContainer.tsx
  src/redux/store.tsx
  src/styles/NavStyle.tsx
Labels: enhancement

#27 Fix navbar layout
  src/App.tsx
  src/components/Nav.tsx
  src/components/NavBase.tsx
  src/components/ProfileBgImg.tsx
  src/pages/MainContainer.tsx
  src/pages/Profile.tsx
Labels: enhancement

#31 Design PostWrite buttons
  src/components/Modal.tsx
  src/components/PostWrite.tsx
Labels: enhancement

#34 Fix post list layout
  src/components/NoticeLayout.tsx
  src/components/PostListLayout.tsx
Labels: bug, enhancement

#37 Api integration
  package-lock.json
  package.json
  src/auth/index.ts
  src/components/MyPoint.tsx
  src/components/NoticeImg.tsx
  src/components/NoticeLayout.tsx
  src/components/NoticeThumbnail.tsx
  src/components/NoticeTitle.tsx
  src/components/NoticeTxt.tsx
  src/components/PostListLayout.tsx
  src/components/PostThumbImg.tsx
  src/components/PostThumbTxt.tsx
  src/components/PostThumbnail.tsx
  src/components/PostTitle.tsx
  src/components/PostWrite.tsx
  src/components/ProfilePoint.tsx
  src/pages/NoticeView.tsx
  src/pages/PostView.tsx
  src/util/ApiUtil.ts
  src/util/RequestAPI.ts
Labels: enhancement
